# Generated by Django 5.2.7 on 2025-10-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=1, max_length=50, verbose_name='氏名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', 'その他'), ('no_answer', '回答しない')], default='no_answer', max_length=20, verbose_name='性別'),
        ),
    ]
