# Generated by Django 5.2.7 on 2025-10-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_full_name_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='生徒番号'),
        ),
    ]
