# Generated by Django 5.2.7 on 2025-10-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', '生徒'), ('TEACHER', '先生'), ('ADMIN', '管理者')], default='STUDENT', max_length=10),
        ),
    ]
