# Generated by Django 5.2.7 on 2025-10-20 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
        ('notebook', '0010_remove_notification_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='head_of_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notebook.grade', verbose_name='担当学年（主任用）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', '生徒'), ('TEACHER', '先生'), ('HEAD_TEACHER', '学年主任'), ('ADMIN', '管理者')], default='STUDENT', max_length=20),
        ),
    ]
