# Generated by Django 5.2.7 on 2025-10-09 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='メモ内容')),
                ('stamp', models.CharField(choices=[('NONE', 'スタンプなし'), ('LIKE', 'イイネ！'), ('GOOD', 'がんばったね！'), ('TRY', '次回に期待'), ('CHECK', '確認済')], default='NONE', max_length=20, verbose_name='スタンプ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dailyrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='notebook.dailyrecord')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '指導メモ',
                'verbose_name_plural': '指導メモ',
                'unique_together': {('dailyrecord', 'teacher')},
            },
        ),
    ]
