# Generated by Django 5.2.7 on 2025-10-09 05:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_memo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='dailyrecord',
            new_name='record',
        ),
        migrations.AlterUniqueTogether(
            name='memo',
            unique_together={('record', 'teacher')},
        ),
    ]
