# Generated by Django 5.2.7 on 2025-10-10 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_rename_dailyrecord_memo_record_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='ログ内容')),
                ('is_important', models.BooleanField(default=False, verbose_name='重要フラグ（会議議題など）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='対象生徒')),
                ('teacher', models.ForeignKey(limit_choices_to={'role__in': ['TEACHER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_logs', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '教師間共有ログ',
                'verbose_name_plural': '教師間共有ログ',
                'ordering': ['-created_at'],
            },
        ),
    ]
