# Generated by Django 5.2.7 on 2025-10-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_teacherlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='mental_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, help_text='メンタル状態を10段階で評価してください（1:最低, 10:最高）。', verbose_name='メンタル（10段階評価）'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='physical_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, help_text='体調を10段階で評価してください（1:最低, 10:最高）。', verbose_name='体調（10段階評価）'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='mental_condition',
            field=models.CharField(blank=True, help_text='メンタルに関して具体的に気づいたこと（例：授業中に集中できた、友人関係で悩んでいるなど）を記入してください。', max_length=100, verbose_name='メンタル補足メモ'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='physical_condition',
            field=models.CharField(blank=True, help_text='体調に関して具体的に気づいたこと（例：昨晩はあまり眠れなかった、頭痛があるなど）を記入してください。', max_length=100, verbose_name='体調補足メモ'),
        ),
    ]
