# Generated by Django 5.2.7 on 2025-10-15 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_dailyrecord_mental_level_dailyrecord_physical_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='is_returned_to_student',
            field=models.BooleanField(default=False, verbose_name='生徒宛通知'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='notebook.dailyrecord'),
        ),
    ]
