# Generated by Django 5.2.7 on 2025-10-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_alter_teacherlog_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecord',
            name='is_returned_to_student',
        ),
    ]
