# Generated by Django 5.2.7 on 2025-10-23 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0010_remove_notification_user_notification_recipient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recordattachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ファイル名'),
        ),
        migrations.AddField(
            model_name='recordattachment',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='Google Driveリンク'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to=settings.AUTH_USER_MODEL, verbose_name='担任教師'),
        ),
        migrations.AlterField(
            model_name='recordattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='record_files/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
    ]
